### ISSUE TITLE
stubInterface<T>() returns incorrect type

### ISSUE THREAD

**Issue by MakotoE** [ttarnowski/ts-sinon#1]
Currently, `stubInterface<T>()` returns `T`, but it should return `SinonStubbedInstance<T>`. I trying out this package and it works great, but the only problem with it is that I'm getting `TS2339: Property 'returns' does not exist on type...` errors. To mitigate this, I cast stub instances to `SinonStubbedInstance<T>` and it works fine.

ts-sinon uses `typescript@^2.6.2`, which does not raise errors when compiled. If I upgrade it to `^3.3.1`, the test file does raise errors.

I would create a pull request to fix this, but I'm still a beginner in Typescript and I probably will not be able to provide a fix that doesn't involve casting.

**Comment by ttarnowski** [comment]
Hello, I have updated the library and type casting seems to be the only solution for the interface stub case which I think after the Typescript upgrade is not really recommended. You can use interface stub with predefined values that you pass as an argument to stubInterface method (please have a look at updated README) instead.

**Comment by MakotoE** [comment]
Thank you for updating the library and readme. The recommended method works perfectly.
