### ISSUE TITLE
Error when using with karma

### ISSUE THREAD

**Issue by sidharthv96** [ttarnowski/ts-sinon#109]
```
Chrome 85.0.4183 (Mac OS X 10.15.6) ERROR
  Uncaught ReferenceError: exports is not defined
  at node_modules/ts-sinon/dist/index.js:9:23
```

Can the module be changed to "UMD" in tsconfig.json so it will work for both node and web envs?

**Comment by ttarnowski** [comment]
is it still an issue?

**Comment by sidharthv96** [comment]
It was a blocker back then. I've switched companies now, @amalvr Can you update? :)
