### ISSUE TITLE
Property 'returns' does not exist on type

### ISSUE THREAD

**Issue by artus** [ttarnowski/ts-sinon#11]
In the REAMDE, it is specified that the following code should work:

```javascript
import * as sinon from 'ts-sinon';

class Test {
    method() { return 'original' }
}
 
const test = new Test();
const testStub = sinon.stubObject<Test>(test);
 
testStub.method.returns('stubbed');
 
expect(testStub.method()).to.equal('stubbed');
```

But this code gives me this error:

> Property 'returns' does not exist on type '() => string'.

What am I doing wrong?

When I cast the created stub to `any`, the code does work without error:

```javascript
const testStub = stubObject<Test>(test) as any;
```

But that will prevent my IDE from doing `intelliSense` completion.

**Comment by ttarnowski** [comment]
Fixed
