### ISSUE TITLE
npm i failed at postinstall

### ISSUE THREAD

**Issue by Whatshiywl** [ttarnowski/ts-sinon#13]
Hi there, I've been having trouble installing the latest (1.0.17) version of this package, as this error keeps happening:

```
> ts-sinon@1.0.17 postinstall /Users/alexandre.bacellar/Dev/webris/restdbbackend/node_modules/ts-sinon
> tsc -p ./ --outDir dist/

../@types/sinon-chai/index.d.ts:107:31 - error TS2694: Namespace 'Chai' has no exported member 'ChaiPlugin'.

107 declare const sinonChai: Chai.ChaiPlugin;
                                  ~~~~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ts-sinon@1.0.17 postinstall: `tsc -p ./ --outDir dist/`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ts-sinon@1.0.17 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I have tried downgrading to 1.0.16 and still the problem remains. It seems to stem from the fact that at that version you moved compilation to the postinstall script, as 1.0.15 seems to work just fine. However, I realise you changed that in order to fix some other problem so maybe there's yet another reason.

**Comment by ttarnowski** [comment]
should be fixed
can you upgrade to the latest version and check again?
