### ISSUE TITLE
Ability to pass overrides for interface properties as well as methods

### ISSUE THREAD

**Issue by jcass8695** [ttarnowski/ts-sinon#134]
It would be great to be able to pass an override for interface properties as well as methods. Currently, that requires two lines - first to stub the interface and secondly to set the value on the stub. As an example, this:

```
interface Test {
    method(): string;
    property: number;
}

const testStub = stubInterface<Test>();
testStub.property = 123;
expect(testStub.property).to.equal(123);
```

should be:
```
interface Test {
    method(): string;
    property: number;
}

const testStub = stubInterface<Test>({ property: 123 });

expect(testStub.property).to.equal(123);
```

**Comment by richard-lopes-ifood** [comment]
Any solution?

**Comment by davidclark87** [comment]
I think this blocks you from using `stubInterface` with readonly properties entirely, since the `testStub.property = 123` workaround will not compile

**Comment by ShellyDCMS** [comment]
Did anyone find a solution for this?
@davidclark87 , I have tried playing with it, and found a solution that can work with read only properties. Further more, it supports getter as well which may come in handy when wanting to stub a class without calling its constructor to avoid side effects.
```diff
+export function stubInterface<T extends object>( methods: ObjectMethodsMap<T> = {},  properties: Partial<T> = {}): StubbedInstance<T> {
+    const object = stubObject<T>(<T>{ ...properties }, methods);
- export function stubInterface<T extends object>(methods: ObjectMethodsMap<T> = {}): StubbedInstance<T> {
-    const object = stubObject<T>(<T> {}, methods);
```
Is this repo still active and receptive for changes? If not, is there a fork you guys are using?

**Comment by jcass8695** [comment]
Hi all, I did not come up with a solution to this. I haven't been working with Typescript or ts-sinon for the last few years, so motivation for me to take a look is low. I'm going to close this as it appears the project is abandoned.

**Comment by ShellyDCMS** [comment]
@jcass8695 , I am willing to take on the maintenance.
