### ISSUE TITLE
sinon.createSandbox() does not exist

### ISSUE THREAD

**Issue by Rolias** [ttarnowski/ts-sinon#21]
The Readme states
> By importing 'ts-sinon' you have access to all sinon methods.
```typescript
import * as sinon from 'ts-sinon'
const sandbox = sinon.createSandbox()
```
Will generate error TS2339: Property 'createSandbox' does not exist

**Comment by ibox4real** [comment]
Sinon is export as default. 
```js
import * as sinon from 'ts-sinon'
const sandbox = sinon.default.createSandbox()
```
or
```js
import sinon from 'ts-sinon'
const sandboc = sinon.createSandbox()
```

**Comment by maugenst** [comment]
I think it would be worthy to update the readme with your remarks... :-)

**Comment by ttarnowski** [comment]
Readme updated.
