### ISSUE TITLE
How to stub console.log

### ISSUE THREAD

**Issue by crystalfp** [ttarnowski/ts-sinon#23]
I'm trying to stub `console.log()` so it does not output anything during unit test.
Using plain sinon my working example is:
```
import { stub } from "sinon"; // eslint-disable-line import/named
stub(console, "log");
```
It works, but I have to suppress an error reported in ESLint. Using `ts-sinon` gives another set of ESLint errors or does not work as in:
```
import * as sinon from "ts-sinon";
sinon.stub(console, "log");
```
So which is the correct method to stub console.log in typescript?
Thanks
mario

**Comment by ttarnowski** [comment]
I think that is probably be due to your eslint configuration not the typescript itself.

**Comment by crystalfp** [comment]
Solved by moving the test environment to `jest`. Not nice for `ts-sinon` but at least now my tests run with no problem.
