### ISSUE TITLE
Stub reset

### ISSUE THREAD

**Issue by gavinvangent** [ttarnowski/ts-sinon#30]
Hey,

Is there functionality to reset a `StubbedInstance<T>`, similar to that of sinon's?

https://sinonjs.org/releases/latest/stubs
```
stub.reset();

Resets both behaviour and history of the stub.

This is equivalent to calling both stub.resetBehavior() and stub.resetHistory()

Updated in sinon@2.0.0

Since sinon@5.0.0

As a convenience, you can apply stub.reset() to all stubs using sinon.reset()
```

Necessary for running many tests with a single instance of a stub.

ie:
```ts
describe('AwesomeServer', () => {
  let kinesis: StubbedInstance<Kinesis>;
  let server: AwesomeServer;
  before(() => {
    kinesis = stubInterface<Kinesis>();
    server = new AwesomeServer(kinesis);
  });

  after(() => {
    server.destroy();
  });

  it('should .....', () => {
    ...
    kinesis.should.have.been.calledOnce;
    ...
  });

  it('should .....', () => {
    ...
    kinesis.should.have.been.calledOnce; 
    // Fails, at this point it would have been called again, so the total
    // call count is 2, however this test only called it once. I'd like to
    // reset the stub before each test
    ...
  });
});
```

What I specifically need is `stub.resetHistory()` as I want to keep the behaviour, so this is more a request about the reset feature as a whole, rather than specifically `stub.reset()`

**Comment by gavinvangent** [comment]
What I specifically need is `stub.resetHistory()` as I want to keep the behaviour, so this is more a request about the reset feature as a whole, rather than specifically `stub.reset()`

**Comment by manvydasu** [comment]
@gavinvangent Did you find anything?

**Comment by gavinvangent** [comment]
@manvydasu No, I didn't.. And If I remember correctly, I just added a comment pointing to this issue, and then incremented the counts

ie:
```ts
kinesis.should.have.callCount(5);

// TODO - reset history - https://github.com/ttarnowski/ts-sinon/issues/30
await server.doSomething();

// kinesis.should.have.callCount(3);
kinesis.should.have.callCount(8);
```

**Comment by ttarnowski** [comment]
isn't it possible to use reset on a stubbed method?

```typescript
interface ITest {
  method1(): string;
}

const t = stubInterface<ITest>();
t.method1.reset();
```

???

**Comment by gavinvangent** [comment]
Just tested it, yeah, i'm able to use:

```ts
t.method1.reset();
t.method1.resetHistory();
t.method1.resetBehavior();
```

Must have slipped me, thanks for the help

Also, i see i wrote things like:

```ts
kinesis.should.have.callCount(8);
```

That should all be something like:

```ts
kinesis.putRecords.should.have.callCount(8);
```

**Comment by ttarnowski** [comment]
👍

**Comment by manvydasu** [comment]
@ttarnowski 
Why is this closed? Don't we want a global solution like sinon.restore() or sinon.reset() to work? If you have multiple stubbed methods it's kinda painful to list all of them and reset

**Comment by nickcollier** [comment]
I'm using this to reset all methods on a stubbed interface

	for (const method in myStub) {
		if (method !== 'constructor') {
			(myStub as any)[method].reset();	
		}
	}
