### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by danilofuchs** [ttarnowski/ts-sinon#32]
I think it's a good idea to upgrade `sinon` to the latest version regularly or adding it as a peerDependency, so users can use which version they think is better for their project.
https://github.com/sinonjs/sinon/blob/master/CHANGELOG.md

**Comment by ttarnowski** [comment]
Thanks for contributing!
Dependencies upgraded.

**Comment by khoover** [comment]
+1 to making sinon a peer dependency instead
