### ISSUE TITLE
stubInterface is deprecated: as it may lead to overwriting stubbed method type

### ISSUE THREAD

**Issue by andsouto** [ttarnowski/ts-sinon#53]
I'm getting the next deprecation warning from tslint:

```
stubInterface is deprecated: as it may lead to overwriting stubbed method type (deprecation)tslint(1)
```

with this code:
```
interface Foo {
  bar: number;
}
foo = stubInterface<Foo>();
```

If I understood the documentation correctly, I'm not using the deprecated behaviour but I'm getting the warning anyway. I guess it is because when the `@deprecated` tag in the method doc string is recognised, it is applied to the whole method signature.

Adding a method signature without the deprecated parameter before the existing one in `index.d.ts` it starts to work as expected. e.g.:
```
export declare function stubInterface<T extends object>(): StubbedInstance<T>;

/**
 * @param methods passing map of methods has become @deprecated as it may lead to overwriting stubbed method type
 */
export declare function stubInterface<T extends object>(methods?: object): StubbedInstance<T>;
```

But I'm not sure what would be the changes needed in the source code as it is not using interfaces.

**Comment by ttarnowski** [comment]
should be fixed with version 2.0.1
