### ISSUE TITLE
Assigning properties with falsy values to a  StubbedInstance can result in unexpected test failures.

### ISSUE THREAD

**Issue by Exigerr** [ttarnowski/ts-sinon#55]
I've been happily using TS-Sinon for a while now and love making use of `stubInterface`. Recently I've encountered a bug with assigning falsy values to properties on a `StubbedInstance`

Normally assigning properties to a `StubbedInstance` like so works fine:
```
const logService = stubInterface<ILogService>();
logService.silent = true;
```

If you try to assign the value of `null`, `undefined`, `false`, `0` or empty string to a property on a `StubbedInstance`, the runtime value triggered from a 'get' will actually be a `sinon.stub`.
This means that any code which is being tested that relies on a strict equality check, will fail.

```
const logService = stubInterface<ILogService>();
logService.silent = false; 
console.log(logService.silent); //value will be a sinon stub.
```

I believe the issue is due to how the Proxy object for the `StubbedInstance` checks if properties exist or not:

https://github.com/ttarnowski/ts-sinon/blob/f09595cbf712f59cd358032b33d18cbc0dbee2fe/src/index.ts#L64

Think this could be resolved by changing the falsy check of `!target[name]` to either:
* `!target.hasOwnProperty(name)`
* `!(name in target)`

Either of those should validate whether or not the object already contains that key. If it does, return the value, else return the stub.

If either of the suggestions would be acceptable, I'd be happy to make a PR with the changes :)

**Comment by ttarnowski** [comment]
I have tried to replicate the issue and console.log returns correct property value regardless of whether the condition in proxy set is !target[name] or !target.hasOwnProperty(name)

Can you upgrade the library and sinon dependency to the latest version?
