### ISSUE TITLE
EventEmitter support

### ISSUE THREAD

**Issue by gavinvangent** [ttarnowski/ts-sinon#84]
I'm trying to stub an interface that extends eventEmitter:

```ts
interface Session extends EventEmitter {
  send: (...) => Promise<string>;
}
```

The function I'm testing looks something like this (dumbed down):

```ts
getSession(opts): Promise<Session> {
  return new Promise(resolve => {
    // `someModule.connect` returns a session instance, which might happen before the connection is complete
    const session = someModule.connect(opts);
    console.log('This is the session:', session);

    // For the example, assume connect succeeds every time
    session.on('connect', () => resolve(session));
  });
}
```

then I stub the interface:

```ts
const session = stubInterface<Session>();
const someModuleConnectStub = sinon.stub(someModule, 'connect');
someModuleConnectStub.returns(session);

setTimeout(() => {
  session.emit('connect');
}, 150);

return getSession(opts)
  .then(result => {
    result.should.be.equal(session);
  });
```

This is the output: 
```sh
this is the session: {
  constructor: [Function: Object],
  should: overwritingMethodWrapper {
    __flags: [Object: null prototype] {
      ssfi: [Function: shouldGetter],
      lockSsfi: undefined,
      object: {},
      message: null
    }
  }
}

Error: Cannot read property 'on' of undefined
```

Am I doing anything wrong here? Is there a reason the stub doesn't have a `.on` function?

I'm guessing the internals of ts-sinon doesn't bind these, and then even if it did, it probably wouldn't have custom code to invoke the function passed into the `.on` function when the emit is invoked? I haven't dug into the code, so this is just a guess.

Any help would be appreciated

**Comment by gavinvangent** [comment]
Turns out the error `Cannot read property 'on' of undefined` is because I had code doing this:

```ts
session.on('connect', onConnect)
  .on('secureConnect', onConnect)
  .on('close', onClose);
```

but `.on()` doesn't return the session, so it works for the first invocation (which returns undefined), then can't invoke the second `.on`

I had to change it to:

```ts
session.on('connect', onConnect);
session.on('secureConnect', onConnect);
session.on('close', onClose);
```

This still didn't work though as the function given to the `.on` function never gets invoked ... 

To get around this, I change my test to:

```ts
const session = stubInterface<Session>();
(session as any).fns = {};
(session as any).on = (name: string, fn: any) => {
  (session as any).fns[name] = fn;
};
(session as any).emit = (name: string, data?: any) => {
  (session as any).fns[name](data);
};

const someModuleConnectStub = sinon.stub(someModule, 'connect');
someModuleConnectStub.returns(session);

setTimeout(() => {
  session.emit('connect');
}, 150);

return getSession(opts)
  .then(result => {
    result.should.be.equal(session);
  });
```

I'm hoping this can be added to ts-sinon instead?

**Comment by ttarnowski** [comment]
Thank you for using my library.
I think the functionality you're looking for is a partial stub for which you have to use stubObject function instead.

Consider following code:
```typescript
class Session extends EventEmitter {
    send() { return "example" }
}

const getSession = (opts): Promise<Session> => {
    return new Promise(resolve => {
        // `someModule.connect` returns a session instance, which might happen before the connection is complete
        const session = someModule.connect(opts);
        console.log('This is the session:', session);

        // For the example, assume connect succeeds every time
        session.on('connect', () => {
            resolve(session);
        });
    });
}

// someModule example
const someModule = { connect: (opts: any[]) => new Session()};

// you need to create an instance of object first
const originSession = new Session();
// now you can create partial (as a second arg provide an array of method names you are going to set custom behaviour for)
const session = stubObject<Session>(originSession, ["send"]);
// do whatever on methods you want to set custom behaviour for
session.send.returns("something");

const someModuleConnectStub = sinon.stub(someModule, 'connect');
someModuleConnectStub.returns(session);

setTimeout(() => {
    session.emit('connect');
}, 150);

getSession(opts)
    .then(result => {
        // cannot use .should on result since it's a partial mock
        expect(result).to.equal(session);
    });
```

Partial mocks allow you to keep some internal behaviour of mocked object while replacing the behaviour of chosen methods.

Alternatively you can refactor your code to use composition over inheritance for Session class -> take EventEmitter object in Session constructor and keep it as a dependency (private member of Session class) then you will be able to test Session behaviour separately (stub EventEmitter and do assertions on what methods have been called with what arguments for 'emit' and 'on').

I hope that'll help with your problem.

**Comment by gavinvangent** [comment]
No, thank you for putting this library out there for us to use; it has made testing with TS so much easier!

I started writing a whole essay here, just to realize that instead, I could do this:

```ts
session.on.callThrough();
session.off.callThrough();
session.emit.callThrough();
```

Just to then test it and find an error: `Unable to find wrapped method`.

Since I'm stubbing an interface that extends EventEmitter, should I not just be able to specify that those functions should just call through, which would give me the default handling I'm looking for?

I'll rewrite my whole long essay after you have a chance to reply to this, if my long essay is still relevant.

Thanks in advance

**Comment by gavinvangent** [comment]
No, thank you for putting this library out there for us to use; its made testing with TS a breeze!

I see how using the `stubObject` in this scenario would be better than `stubInterface` and will implement that. Thanks for the help.

For anyone reading this, it comes down to the difference between actually having an instance of an EventEmitter (or something that extends it) which has all the properties implemented and ready to be used, versus having a definition of an EventEmitter (ie, a template, a schema, a skeleton, an interface) where the properties are just placeholders for code that could be defined and executed.

As for the alternative, thanks, but for this scenario I have that wouldn't work as I'm mocking a resource from another node module and can't actually control the internals; I can't convert it to use composition rather than inheritance. But another good suggestion, thanks
